# Generated by Django 5.1.3 on 2025-01-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='Nb_article',
            field=models.IntegerField(default=0),
        ),
    ]
