# Generated by Django 5.1.3 on 2025-01-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_categorie_nb_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Nom_categorie',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
