# Generated by Django 5.1.3 on 2025-01-15 04:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_categorie_nom_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_article', models.CharField(max_length=50, unique=True)),
                ('Quantite_atc', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('Prix_atc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('Description_atc', models.TextField(blank=True, default='Pas de description disponible pour cette article')),
                ('Statut_atc', models.CharField(choices=[('disponible', 'Disponible'), ('non disponible', 'Non disponible')], default='disponible', max_length=15)),
                ('Image_atc', models.ImageField(blank=True, null=True, upload_to='images_articles/')),
                ('Categorie_atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.categorie')),
            ],
        ),
    ]
