# Generated by Django 5.1.3 on 2025-01-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Description_atc',
            field=models.TextField(blank=True, default='Pas de description disponible pour cet article'),
        ),
    ]
