# Generated by Django 5.1.3 on 2025-01-16 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_article_description_atc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Description_atc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='Quantite_atc',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
