# Generated by Django 5.1.3 on 2025-01-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_article_description_atc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Prix_atc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
