# Generated by Django 5.1.3 on 2025-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_article_prix_atc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Statut_atc',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non disponible', 'Non disponible')], max_length=15),
        ),
    ]
