# Generated by Django 5.1.3 on 2025-01-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_article_statut_atc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Statut_atc',
        ),
    ]
