# Generated by Django 5.1.3 on 2025-01-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_remove_article_statut_atc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Description_atc',
            new_name='Description_atc1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Image_atc',
            new_name='Image_atc1',
        ),
        migrations.AddField(
            model_name='article',
            name='Description_atc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='Image_atc2',
            field=models.ImageField(blank=True, null=True, upload_to='images_articles/'),
        ),
        migrations.AddField(
            model_name='article',
            name='Image_atc3',
            field=models.ImageField(blank=True, null=True, upload_to='images_articles/'),
        ),
        migrations.AddField(
            model_name='article',
            name='Image_atc4',
            field=models.ImageField(blank=True, null=True, upload_to='images_articles/'),
        ),
    ]
