# Generated by Django 5.1.3 on 2025-01-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_rename_description_atc_article_description_atc1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Description_atc1',
            new_name='Description1_atc',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Description_atc2',
            new_name='Description2_atc',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Image_atc1',
            new_name='Image1_atc',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Image_atc2',
            new_name='Image2_atc',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Image_atc3',
            new_name='Image3_atc',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Image_atc4',
            new_name='Image4_atc',
        ),
    ]
