# Generated by Django 5.1.3 on 2025-01-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_article_description1_atc'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Marque_atc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
