# Generated by Django 5.1.3 on 2025-01-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_article_marque_atc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_service', models.CharField(max_length=50, unique=True)),
                ('Description_svc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
