# Generated by Django 5.1.3 on 2025-01-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Image_svc',
            field=models.ImageField(blank=True, null=True, upload_to='images_services/'),
        ),
    ]
