# Generated by Django 5.1.3 on 2025-03-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_services_image_svc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_cat_categorie', models.CharField(max_length=30, unique=True)),
                ('Nb_article', models.IntegerField(default=0)),
                ('Categorie_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.categorie')),
            ],
        ),
    ]
